name: Style Builder CI

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.1.0]

    steps:
      - uses: actions/checkout@v3

      # (1) -> Preparations
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # (2) -> Install and initialize
      - name: Install
        run: |
          npm install
          cd wizard-style-builder
          npm install
          npm run init

      # (3) -> Run tests
      - name: Test
        run: |
          cd wizard-style-builder
          npm run test

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: [test]

    strategy:
      matrix:
        node-version: [18]

    env:
      PUBLIC_IMAGE: datastewardshipwizard/wizard-style-builder
      PRIVATE_IMAGE: ${{ secrets.PRIVATE_REGISTRY_URL }}/wizard-style-builder
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      PRIVATE_REGISTRY_URL: ${{ secrets.PRIVATE_REGISTRY_URL }}
      DOCKER_META_CONTEXT: './wizard-style-builder'
      DOCKER_META_FILE: './wizard-style-builder/docker/Dockerfile'
      DOCKER_META_PLATFORMS: 'linux/amd64,linux/arm64'

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # (1) -> Preparations
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # (2) -> Install dependencies
      - name: Install
        run: |
          npm ci
          cd wizard-style-builder
          npm ci

      # (3) -> Build app and Docker image
      - name: Build
        run: |
          cd wizard-style-builder
          npm run init

      # TEST DOCKER IMAGE BUILD
      - name: Docker meta [test]
        id: meta-test
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.PUBLIC_IMAGE }}
          tags: |
            type=sha

      - name: Docker build+push [test]
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKER_META_CONTEXT }}
          file: ${{ env.DOCKER_META_FILE }}
          platforms: ${{ env.DOCKER_META_PLATFORMS }}
          push: false
          tags: ${{ steps.meta-test.outputs.tags }}
          labels: ${{ steps.meta-test.outputs.labels }}

      # PRIVATE: DOCKER REGISTRY
      - name: Docker login [private]
        uses: docker/login-action@v2
        if: env.PRIVATE_REGISTRY_URL != ''
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Docker meta [private]
        uses: docker/metadata-action@v4
        id: meta-private
        if: env.PRIVATE_REGISTRY_URL != ''
        with:
          images: |
            ${{ secrets.PRIVATE_IMAGE }}
          tags: |
            type=ref,event=branch

      - name: Docker build+push [private]
        uses: docker/build-push-action@v3
        if: env.PRIVATE_REGISTRY_URL != '' && steps.meta-private.outputs.tags != ''
        with:
          context: ${{ env.DOCKER_META_CONTEXT }}
          file: ${{ env.DOCKER_META_FILE }}
          platforms: ${{ env.DOCKER_META_PLATFORMS }}
          push: false  # TODO: change when ready
          tags: ${{ steps.meta-private.outputs.tags }}
          labels: ${{ steps.meta-private.outputs.labels }}

      # PUBLIC: DOCKER HUB
      - name: Docker login [public]
        uses: docker/login-action@v2
        if: env.DOCKER_HUB_USERNAME != ''
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker meta [public]
        uses: docker/metadata-action@v4
        if: env.DOCKER_HUB_USERNAME != ''
        id: meta-public
        with:
          images: |
            ${{ env.PUBLIC_IMAGE_PREFIX }}/${{ steps.docker-image-name.outputs.NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Docker build+push [public]
        uses: docker/build-push-action@v3
        if: env.DOCKER_HUB_USERNAME != '' && steps.meta-public.outputs.tags != ''
        with:
          context: ${{ env.DOCKER_META_CONTEXT }}
          file: ${{ env.DOCKER_META_FILE }}
          platforms: ${{ env.DOCKER_META_PLATFORMS }}
          push: false  # TODO: change when ready
          tags: ${{ steps.meta-public.outputs.tags }}
          labels: ${{ steps.meta-public.outputs.labels }}
